spring:
  datasource:
    url: jdbc:mysql://localhost/spring
    username: testuser
    password: testuser
    driverClassName: com.mysql.jdbc.Driver
security:
  basic:
    enabled: false
debug: true
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG

